version: "3.9"
services:
  telegram-bot:
    image: philosopher-discord-bot:latest
    build: .
    container_name: philosopher-discord-bot
    restart: unless-stopped
    environment:
      - COMMAND_PREFIX='!'
      - WEBHOOK_NAME='uwu nyanis going on hewe'
      - WEBHOOK_CREATED_RESPONSE='phiwowoswowophizing mwessages wike a-a gwowoowod bwowot (⑅˘꒳˘)'
      - WEBHOOK_REMOVED_RESPONSE='weaving mwessages as fay awe wike a-a bad bwot (⌯˃̶᷄ ﹏ ˂̶᷄⌯)ﾟ'
    env_file:
      - ./.env
networks:
  default:
    name: philosopher-discord-bot-network
    driver: bridge