version: "3.9"
services:
  telegram-bot:
    image: philosopher-discord-bot:latest
    build: .
    container_name: philosopher-discord-bot
    restart: unless-stopped
    env_file:
      - ./.env
networks:
  default:
    name: philosopher-discord-bot-network
    driver: bridge
